# Generated by Django 5.2.14 on 2026-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0004_init_p2_semesters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("moodle_id", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="qcm.tag"
            ),
        ),
    ]
