# Generated by Django 5.2.14 on 2026-05-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0005_add_tag_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="quizsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="QuizSessionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_questions",
                        to="qcm.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_questions",
                        to="qcm.quizsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("session", "question")},
            },
        ),
        migrations.AddField(
            model_name="quizsession",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                through="qcm.QuizSessionQuestion",
                to="qcm.question",
            ),
        ),
    ]
