# Generated by Django 5.2.14 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0006_training_interface_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="shuffle_answers",
            field=models.BooleanField(default=True),
        ),
    ]
