# Generated by Django 5.2.14 on 2026-06-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0007_add_shuffle_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("annee", "Annales par année"),
                            ("souscategorie", "Sous-catégorie de cours"),
                            ("chapitre", "Chapitre"),
                        ],
                        default="annee",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_categories",
                        to="qcm.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie de tag",
                "verbose_name_plural": "catégories de tags",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="qcm.tagcategory",
            ),
        ),
    ]
