# Generated by Django 5.2.14 on 2026-06-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0008_add_tagcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="parent_ec",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__tag_type": "souscategorie"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapter_tags",
                to="qcm.tag",
                verbose_name="EC parente (pour les tags chapitres)",
            ),
        ),
    ]
