# Generated by Django 5.2.14 on 2026-06-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0009_add_tag_parent_ec"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapter_tags",
                to="qcm.course",
                verbose_name="Cours (pour les tags chapitres)",
            ),
        ),
    ]
