# Generated by Django 5.2.14 on 2026-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0010_add_tag_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'inscription",
                "verbose_name_plural": "Demandes d'inscription",
                "ordering": ["-created_at"],
            },
        ),
    ]
