# Generated by Django 5.2.14 on 2026-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0011_add_registration_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="certificate",
            field=models.FileField(
                blank=True,
                upload_to="certificates/",
                verbose_name="Certificat de scolarité (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
    ]
