# Generated by Django 5.2.14 on 2026-06-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0013_add_user_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du menu"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="packages",
                        to="qcm.course",
                        verbose_name="Cours inclus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu d'inscription",
                "verbose_name_plural": "Menus d'inscription",
                "ordering": ["name"],
            },
        ),
    ]
