# Generated by Django 5.2.14 on 2026-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0014_add_course_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepackage",
            name="parcours",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "Ancien PASS"),
                    ("LAS1", "Ancien LAS1"),
                    ("LAS2", "Ancien LAS2"),
                ],
                max_length=10,
                verbose_name="Parcours",
            ),
        ),
        migrations.AddField(
            model_name="coursepackage",
            name="year",
            field=models.CharField(
                blank=True,
                choices=[("P2", "P2 (DFGSM2)"), ("D1", "D1 (DFGSM3)")],
                max_length=10,
                verbose_name="Année",
            ),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="parcours",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "Ancien PASS"),
                    ("LAS1", "Ancien LAS1"),
                    ("LAS2", "Ancien LAS2"),
                ],
                max_length=10,
                verbose_name="Parcours antérieur",
            ),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="year",
            field=models.CharField(
                choices=[("P2", "P2 (DFGSM2)"), ("D1", "D1 (DFGSM3)")],
                default="",
                max_length=10,
                verbose_name="Année d'entrée",
            ),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="message",
            field=models.TextField(blank=True, verbose_name="Message complémentaire"),
        ),
    ]
