# Generated by Django 5.2.14 on 2026-06-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0015_add_year_parcours_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Errata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("points", "Erreur d'attribution de points"),
                            ("correction", "Erreur dans la correction"),
                            ("image", "Image manquante"),
                            ("tag", "Erreur de tag"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description du problème"),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Note admin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Accepté"),
                            ("rejected", "Refusé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concerned_answers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="erratas",
                        to="qcm.answer",
                        verbose_name="Réponses concernées",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erratas",
                        to="qcm.question",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erratas_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erratas_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="erratas",
                        to="qcm.tag",
                        verbose_name="Tags suggérés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Errata",
                "verbose_name_plural": "Erratas",
                "ordering": ["-created_at"],
            },
        ),
    ]
