# Generated by Django 5.2.14 on 2026-06-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0017_add_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="moodle_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
