# Generated by Django 5.2.14 on 2026-06-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0018_question_moodle_id_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="errata",
            name="qroc_suggested_fraction",
            field=models.FloatField(
                blank=True,
                help_text="1.0 = réponse complète, 0.7 = réponse partielle, etc.",
                null=True,
                verbose_name="Fraction suggérée (QROC)",
            ),
        ),
        migrations.AddField(
            model_name="errata",
            name="qroc_suggested_text",
            field=models.TextField(blank=True, verbose_name="Réponse suggérée (QROC)"),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="is_self_evaluated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="qroc_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="errata",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description du problème"),
        ),
        migrations.AlterField(
            model_name="errata",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("points", "Erreur d'attribution de points"),
                    ("correction", "Erreur dans la correction"),
                    ("image", "Image manquante"),
                    ("tag", "Erreur de tag"),
                    ("qroc_answer", "Ma réponse est correcte (QROC)"),
                    ("autre", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_answers",
                to="qcm.answer",
            ),
        ),
    ]
