# Generated by Django 5.2.14 on 2026-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0019_qroc_useranswer_errata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="moodle_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
