# Generated by Django 5.2.14 on 2026-06-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0020_tag_moodle_id_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moodle_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="question_images/")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="qcm.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de question",
                "verbose_name_plural": "Images de questions",
                "unique_together": {("question", "moodle_filename")},
            },
        ),
    ]
