# Generated by Django 5.2.14 on 2026-06-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0021_questionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="fraction_override",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="qtype",
            field=models.CharField(
                choices=[
                    ("multichoice", "Choix multiple"),
                    ("shortanswer", "Réponse courte"),
                    ("match", "Appariement"),
                    ("ddimageortext", "Légende interactive"),
                ],
                default="multichoice",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ImageDragItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
                ("label", models.CharField(max_length=500)),
                ("draggroup", models.IntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drag_items",
                        to="qcm.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étiquette drag",
                "verbose_name_plural": "Étiquettes drag",
                "ordering": ["no"],
                "unique_together": {("question", "no")},
            },
        ),
        migrations.CreateModel(
            name="ImageDropZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
                ("xleft", models.IntegerField()),
                ("ytop", models.IntegerField()),
                ("correct_drag_no", models.IntegerField()),
                ("correct_label", models.CharField(max_length=500)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_zones",
                        to="qcm.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone drop",
                "verbose_name_plural": "Zones drop",
                "ordering": ["no"],
                "unique_together": {("question", "no")},
            },
        ),
    ]
