# Generated by Django 5.2.14 on 2026-06-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0023_add_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon_emoji",
                    models.CharField(default="🏆", max_length=10, verbose_name="Emoji"),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Argent"),
                            ("gold", "Or"),
                        ],
                        max_length=10,
                        verbose_name="Rareté",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("questions_count", "Nombre de questions réalisées"),
                            ("correct_count", "Nombre de bonnes réponses"),
                            (
                                "questions_count_tag",
                                "Nombre de questions réalisées (tag)",
                            ),
                            ("correct_count_tag", "Nombre de bonnes réponses (tag)"),
                            ("perfect_session", "Session parfaite (20/20)"),
                            ("sessions_count", "Nombre de sessions complétées"),
                        ],
                        max_length=30,
                        verbose_name="Type de condition",
                    ),
                ),
                (
                    "condition_value",
                    models.IntegerField(default=1, verbose_name="Valeur seuil"),
                ),
                (
                    "condition_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trophies",
                        to="qcm.tag",
                        verbose_name="Tag (pour trophées par EC)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trophée",
                "verbose_name_plural": "Trophées",
                "ordering": ["-rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserTrophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trophies",
                        to="qcm.trophy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trophies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trophée utilisateur",
                "verbose_name_plural": "Trophées utilisateurs",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "trophy")},
            },
        ),
    ]
