# Generated by Django 5.2.14 on 2026-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0024_add_trophy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trophy",
            options={"verbose_name": "Trophée", "verbose_name_plural": "Trophées"},
        ),
        migrations.AlterField(
            model_name="trophy",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("questions_count", "Nombre de questions réalisées"),
                    ("correct_count", "Nombre de bonnes réponses"),
                    ("questions_count_tag", "Nombre de questions réalisées (tag)"),
                    ("correct_count_tag", "Nombre de bonnes réponses (tag)"),
                    ("perfect_session", "Session parfaite (20/20)"),
                    ("sessions_count", "Nombre de sessions complétées"),
                    ("erratas_accepted", "Erratas acceptés par l'admin"),
                ],
                max_length=30,
                verbose_name="Type de condition",
            ),
        ),
    ]
