# Generated by Django 5.2.14 on 2026-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0025_trophy_erratas_accepted_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="trophy",
            name="study_year",
            field=models.CharField(
                blank=True,
                choices=[("P2", "P2"), ("D1", "D1")],
                default="",
                max_length=5,
                verbose_name="Année",
            ),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("questions_count", "Nombre de questions réalisées"),
                    ("correct_count", "Nombre de bonnes réponses"),
                    ("questions_count_tag", "Nombre de questions réalisées (tag)"),
                    ("correct_count_tag", "Nombre de bonnes réponses (tag)"),
                    ("perfect_session", "Session parfaite (20/20)"),
                    ("sessions_count", "Nombre de sessions complétées"),
                    ("erratas_accepted", "Erratas acceptés par l'admin"),
                    ("zero_score_count", "Questions avec score nul (0 point)"),
                ],
                max_length=30,
                verbose_name="Type de condition",
            ),
        ),
    ]
