# Generated by Django 5.2.14 on 2026-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0026_trophy_study_year_and_zero_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="trophy",
            name="hidden",
            field=models.BooleanField(
                default=False, verbose_name="Masqué avant obtention"
            ),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="study_year",
            field=models.CharField(
                blank=True,
                choices=[("ALL", "Transversal"), ("P2", "P2"), ("D1", "D1")],
                default="",
                max_length=5,
                verbose_name="Année",
            ),
        ),
    ]
