# Generated by Django 5.2.14 on 2026-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0027_trophy_hidden_and_year_all"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophy",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("questions_count", "Nombre de questions réalisées"),
                    ("correct_count", "Nombre de bonnes réponses"),
                    ("questions_count_tag", "Nombre de questions réalisées (tag)"),
                    ("correct_count_tag", "Nombre de bonnes réponses (tag)"),
                    ("perfect_session", "Session parfaite (20/20)"),
                    ("sessions_count", "Nombre de sessions complétées"),
                    ("erratas_accepted", "Erratas acceptés par l'admin"),
                    ("zero_score_count", "Questions avec score nul (0 point)"),
                    (
                        "zero_score_count_tag",
                        "Questions avec score nul (0 point) — tag",
                    ),
                ],
                max_length=30,
                verbose_name="Type de condition",
            ),
        ),
    ]
