# Generated by Django 5.2.14 on 2026-06-09 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0028_trophy_zero_score_count_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophy",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("questions_count", "Nombre de questions réalisées"),
                    ("correct_count", "Nombre de bonnes réponses"),
                    ("questions_count_tag", "Nombre de questions réalisées (tag)"),
                    ("correct_count_tag", "Nombre de bonnes réponses (tag)"),
                    ("perfect_session", "Session parfaite (20/20)"),
                    ("sessions_count", "Nombre de sessions complétées"),
                    ("erratas_accepted", "Erratas acceptés par l'admin"),
                    ("zero_score_count", "Questions avec score nul (0 point)"),
                    (
                        "zero_score_count_tag",
                        "Questions avec score nul (0 point) — tag",
                    ),
                    ("login_count", "Nombre de connexions à la plateforme"),
                    ("consecutive_days", "Jours de connexion consécutifs"),
                ],
                max_length=30,
                verbose_name="Type de condition",
            ),
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connexion",
                "verbose_name_plural": "Connexions",
                "indexes": [
                    models.Index(
                        fields=["user", "logged_at"],
                        name="qcm_loginev_user_id_b73680_idx",
                    )
                ],
            },
        ),
    ]
