# Generated by Django 5.2.14 on 2026-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0029_add_login_event_and_login_trophies"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="hidden_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
