# Generated by Django 5.2.14 on 2026-06-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0030_quizsession_hidden_by_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageDropZoneLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_labels",
                        to="qcm.imagedropzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Label accepté (zone)",
                "verbose_name_plural": "Labels acceptés (zone)",
            },
        ),
    ]
