# Generated by Django 5.2.14 on 2026-07-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0031_imagedropzonelabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="qcm.course",
            ),
        ),
    ]
