# Generated by Django 5.2.14 on 2026-07-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0034_remove_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="errata",
            name="concerned_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="erratas",
                to="qcm.imagedropzone",
                verbose_name="Zone concernée (légende interactive)",
            ),
        ),
        migrations.AlterField(
            model_name="errata",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("points", "Erreur d'attribution de points"),
                    ("correction", "Erreur dans la correction"),
                    ("image", "Image manquante"),
                    ("tag", "Erreur de tag"),
                    ("qroc_answer", "Ma réponse est correcte (QROC)"),
                    (
                        "ddi_answer",
                        "Une de mes réponses est correcte (légende interactive)",
                    ),
                    ("autre", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="errata",
            name="qroc_suggested_text",
            field=models.TextField(
                blank=True, verbose_name="Réponse suggérée (QROC / légende de zone)"
            ),
        ),
    ]
