# Generated by Django 5.2.14 on 2026-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0035_errata_concerned_zone_alter_errata_error_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("light", "Clair"), ("dark", "Sombre")],
                default="",
                max_length=5,
            ),
        ),
    ]
