# Generated by Django 5.2.14 on 2026-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qcm", "0036_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
