from django.urls import path

from . import views, views_admin


app_name = "qcm"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("entrainement/", views.ConfigurationView.as_view(), name="configuration"),
    path(
        "entrainement/session/<int:pk>/",
        views.QuestionView.as_view(),
        name="question",
    ),
    path(
        "entrainement/session/<int:pk>/check/",
        views.CheckView.as_view(),
        name="check",
    ),
    path(
        "entrainement/session/<int:pk>/check-qroc/",
        views.CheckQROCSelfView.as_view(),
        name="check_qroc",
    ),
    path(
        "entrainement/session/<int:pk>/fin/",
        views.FinView.as_view(),
        name="fin",
    ),
    path("entrainement/tags/", views.TagsView.as_view(), name="tags"),
    path("entrainement/chapters/", views.ChaptersView.as_view(), name="chapters"),
    path("statistiques/", views.StatsView.as_view(), name="stats"),
    path("errata/", views.ErrataListView.as_view(), name="errata_list"),
    path(
        "errata/<int:pk>/accept/",
        views.ErrataAcceptView.as_view(),
        name="errata_accept",
    ),
    path(
        "errata/<int:pk>/reject/",
        views.ErrataRejectView.as_view(),
        name="errata_reject",
    ),
    path(
        "errata/<int:pk>/feedback/",
        views.ErrataFeedbackView.as_view(),
        name="errata_feedback",
    ),
    path(
        "errata/<int:pk>/upload-image/",
        views.ErrataUploadImageView.as_view(),
        name="errata_upload_image",
    ),
    path(
        "notifications/<int:pk>/mark-read/",
        views.NotificationMarkReadView.as_view(),
        name="notification_mark_read",
    ),
    path(
        "notifications/mark-all-read/",
        views.NotificationMarkAllReadView.as_view(),
        name="notification_mark_all_read",
    ),
    path(
        "errata/question/<int:question_id>/",
        views.ErrataSubmitView.as_view(),
        name="errata_submit",
    ),
    path("historique/", views.HistoryView.as_view(), name="history"),
    path(
        "historique/session/<int:pk>/",
        views.SessionDetailView.as_view(),
        name="session_detail",
    ),
    path(
        "statistiques/cours/<int:course_id>/",
        views.CourseStatsView.as_view(),
        name="course_stats",
    ),
    path(
        "questions/upload/",
        views.AdminQuestionsUploadView.as_view(),
        name="questions_upload",
    ),
    path(
        "questions/upload/preview/",
        views.AdminQuestionsPreviewView.as_view(),
        name="questions_preview",
    ),
    path(
        "questions/confirmer/",
        views.AdminQuestionsConfirmView.as_view(),
        name="questions_confirm",
    ),
    path("inscription/", views.InscriptionView.as_view(), name="inscription"),
    path(
        "inscription/merci/",
        views.InscriptionDoneView.as_view(),
        name="inscription_done",
    ),
    # ── Admin site web ────────────────────────────────────────────────────────
    path(
        "admin-site/",
        views_admin.AdminDashboardView.as_view(),
        name="admin_dashboard",
    ),
    path(
        "admin-site/demandes/",
        views_admin.AdminRegistrationsView.as_view(),
        name="admin_registrations",
    ),
    path(
        "admin-site/demandes/<int:pk>/accepter/",
        views_admin.AdminAcceptRegistrationView.as_view(),
        name="admin_registration_accept",
    ),
    path(
        "admin-site/demandes/<int:pk>/refuser/",
        views_admin.AdminRejectRegistrationView.as_view(),
        name="admin_registration_reject",
    ),
    path(
        "admin-site/utilisateurs/",
        views_admin.AdminUsersView.as_view(),
        name="admin_users",
    ),
    path(
        "admin-site/utilisateurs/<int:pk>/toggle/",
        views_admin.AdminToggleUserView.as_view(),
        name="admin_user_toggle",
    ),
    path(
        "admin-site/utilisateurs/<int:pk>/supprimer/",
        views_admin.AdminDeleteUserView.as_view(),
        name="admin_user_delete",
    ),
    path(
        "admin-site/utilisateurs/<int:pk>/changer-annee/",
        views_admin.AdminChangeUserYearView.as_view(),
        name="admin_user_change_year",
    ),
    path(
        "admin-site/questions/",
        views_admin.AdminQuestionsView.as_view(),
        name="admin_questions",
    ),
    path(
        "admin-site/questions/ajouter/",
        views_admin.AdminQuestionAddView.as_view(),
        name="admin_question_add",
    ),
    path(
        "admin-site/questions/<int:pk>/modifier/",
        views_admin.AdminQuestionEditView.as_view(),
        name="admin_question_edit",
    ),
    path(
        "admin-site/questions/<int:pk>/supprimer/",
        views_admin.AdminQuestionDeleteView.as_view(),
        name="admin_question_delete",
    ),
    path(
        "admin-site/cours/",
        views_admin.AdminCoursesView.as_view(),
        name="admin_courses",
    ),
    path(
        "admin-site/cours/<int:pk>/",
        views_admin.AdminCourseEditView.as_view(),
        name="admin_course_edit",
    ),
    path(
        "admin-site/tags/",
        views_admin.AdminTagsView.as_view(),
        name="admin_tags",
    ),
    path(
        "admin-site/tags/<int:pk>/supprimer/",
        views_admin.AdminTagDeleteView.as_view(),
        name="admin_tag_delete",
    ),
]
